### ISSUE TITLE
Add a software license

### ISSUE THREAD

**Issue by KM4YRI** [ko7m/Si570#2]
Edit: I originally wrote to ask if you could pick a license and add it to the repo.  I apparently missed line#4 in Si570.cpp that puts it under the MIT license.  I've deleted the original issue text for that reason.

So, I guess all that I'm asking for at this point would be to add a file "LICENSE.md" to the repo with the text of the MIT license, which can be found here: https://opensource.org/licenses/MIT  .. If you'd be able to add it to the repo that might make it easier for people to see.  

Thanks!

-KM4YRI

**Comment by ko7m** [comment]
Hello!  Sorry to be slow responding.  I am honored that you find this bit of code useful and have no issues with you using it in any way that makes sense to you.  I have added the LICENSE.md file with the text of the MIT license to the repo as requested.
